from enum import Enum


class AttackType(str, Enum):
    PROMPT_INJECTION = "PROMPT_INJECTION"
    SYSTEM_PROMPT_EXTRACTION = "SYSTEM_PROMPT_EXTRACTION"
    ROLE_MANIPULATION = "ROLE_MANIPULATION"
    INSTRUCTION_OVERRIDE = "INSTRUCTION_OVERRIDE"
    JAILBREAK = "JAILBREAK"
    DATA_EXFILTRATION = "DATA_EXFILTRATION"
    TOOL_MANIPULATION = "TOOL_MANIPULATION"
    OBFUSCATION = "OBFUSCATION"
    INDIRECT_INJECTION = "INDIRECT_INJECTION"
    SAFE = "SAFE"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class Decision(str, Enum):
    ALLOW = "ALLOW"
    WARN = "WARN"
    BLOCK = "BLOCK"
